# Generated by Django 5.2.5 on 2025-08-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
    ]
