# Generated by Django 5.2.5 on 2025-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
